---
- name: test
  hosts: localhost
  become: true
  tasks:
  - name: List Repositories
    ansible.builtin.uri:
      url: "https://nx02.localdomain:8443/service/rest/v1/components?repository=test-few"
      user: admin
      password: admin
      force_basic_auth: true
      method: GET
      status_code: 200
      validate_certs: false
    register: repo